//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankField
    {
        public BankField()
        {
            this.BankTask_Field = new HashSet<BankTask_Field>();
            this.Equipment_TechField = new HashSet<Equipment_TechField>();
            this.JobTaskField = new HashSet<JobTaskField>();
        }
    
        public int BankFieldID { get; set; }
        public int FieldPoolID { get; set; }
        public string FieldNameStr { get; set; }
        public Nullable<int> CatalogItemID { get; set; }
    
        public virtual FieldPool FieldPool { get; set; }
        public virtual ICollection<BankTask_Field> BankTask_Field { get; set; }
        public virtual ICollection<Equipment_TechField> Equipment_TechField { get; set; }
        public virtual ICollection<JobTaskField> JobTaskField { get; set; }
    }
}
