//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTask
    {
        public BankTask()
        {
            this.BankTask_Field = new HashSet<BankTask_Field>();
        }
    
        public int BankTaskID { get; set; }
        public string TaskName { get; set; }
        public string ManagerNotes { get; set; }
    
        public virtual ICollection<BankTask_Field> BankTask_Field { get; set; }
    }
}
