//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Employee = new HashSet<Employee>();
            this.JobRefubrish = new HashSet<JobRefubrish>();
        }
    
        public int BranchID { get; set; }
        public string BranceName { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<JobRefubrish> JobRefubrish { get; set; }
    }
}
