//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Job = new HashSet<Job>();
            this.Machine = new HashSet<Machine>();
            this.User = new HashSet<User>();
            this.SupplierProduct = new HashSet<SupplierProduct>();
            this.ManufactureProducts = new HashSet<SupplierProduct>();
            this.Quote = new HashSet<Quote>();
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ClientParentID { get; set; }
        public string Logo { get; set; }
        public string vwParentsName1 { get; set; }
        public string vwParentsName2 { get; set; }
        public string vwChildsID { get; set; }
        public bool HasVbService { get; set; }
        public bool ShowInVb { get; set; }
        public bool ShowInRefubrish { get; set; }
        public bool IsClient { get; set; }
        public bool IsSupplier { get; set; }
        public bool IsManufacture { get; set; }
        public bool ShowInAlignment { get; set; }
        public Nullable<int> AccountingID { get; set; }
        public Nullable<int> ChatPeyID { get; set; }
        public string ClientNameEnglish { get; set; }
        public string ClientParentNameEnglish { get; set; }
        public string ClientFullNameEnglish { get; set; }
    
        public virtual ICollection<Job> Job { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProduct { get; set; }
        public virtual ICollection<SupplierProduct> ManufactureProducts { get; set; }
        public virtual ICollection<Quote> Quote { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
