//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactInfoID { get; set; }
        public int ObjID { get; set; }
        public Common.ObjType ObjType { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string ExtraPhone { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string JobTitle { get; set; }
        public string EmailPassword { get; set; }
    }
}
