//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicGroupField
    {
        public DynamicGroupField()
        {
            this.JobRefubrish_StepField = new HashSet<JobRefubrish_StepField>();
            this.MachinePart_TechField = new HashSet<MachinePart_TechField>();
        }
    
        public int DynamicGroupFieldID { get; set; }
        public int DynamicGroupID { get; set; }
        public int FieldPoolID { get; set; }
        public string FieldNameStr { get; set; }
        public bool IsRequired { get; set; }
        public int OrderVal { get; set; }
        public bool IsForQuote { get; set; }
        public Nullable<int> CatalogItemID { get; set; }
    
        public virtual DynamicGroup DynamicGroup { get; set; }
        public virtual FieldPool FieldPool { get; set; }
        public virtual ICollection<JobRefubrish_StepField> JobRefubrish_StepField { get; set; }
        public virtual ICollection<MachinePart_TechField> MachinePart_TechField { get; set; }
        public virtual CatalogItem CatalogItem { get; set; }
    }
}
