//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.JobVibration = new HashSet<JobVibration>();
            this.JobVibration1 = new HashSet<JobVibration>();
            this.EmployeeRole = new HashSet<EmployeeRole>();
            this.JobRefubrish_Step = new HashSet<JobRefubrish_Step>();
            this.JobAlignment = new HashSet<JobAlignment>();
            this.Job = new HashSet<Job>();
            this.QuoteTalk = new HashSet<QuoteTalk>();
            this.Quote = new HashSet<Quote>();
            this.EmployeeLog = new HashSet<EmployeeLog>();
            this.JobTaskEmployee = new HashSet<JobTaskEmployee>();
        }
    
        public int EmployeeID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public bool ShowSettings { get; set; }
        public bool ShowVB { get; set; }
        public bool ShowClientSettings { get; set; }
        public bool ShowRefubrish { get; set; }
        public int BranchID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool ShowCatalog { get; set; }
        public bool ShowQuote { get; set; }
        public bool ShowAlignment { get; set; }
        public bool ShowBalancing { get; set; }
        public bool ShowManagReports { get; set; }
        public bool ShowFieldsEdit { get; set; }
    
        public virtual ICollection<JobVibration> JobVibration { get; set; }
        public virtual ICollection<JobVibration> JobVibration1 { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRole { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<JobRefubrish_Step> JobRefubrish_Step { get; set; }
        public virtual ICollection<JobAlignment> JobAlignment { get; set; }
        public virtual ICollection<Job> Job { get; set; }
        public virtual ICollection<QuoteTalk> QuoteTalk { get; set; }
        public virtual ICollection<Quote> Quote { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLog { get; set; }
        public virtual ICollection<JobTaskEmployee> JobTaskEmployee { get; set; }
    }
}
