//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public int EmployeeLogID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string Entity { get; set; }
        public int EntityId { get; set; }
        public string Action { get; set; }
        public int EmployeeID { get; set; }
        public string Param { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
