//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldPool
    {
        public FieldPool()
        {
            this.DynamicGroupField = new HashSet<DynamicGroupField>();
            this.CatalogItem = new HashSet<CatalogItem>();
            this.QuoteVersionItem = new HashSet<QuoteVersionItem>();
            this.BankField = new HashSet<BankField>();
        }
    
        public int FieldPoolID { get; set; }
        public string FieldNameStr { get; set; }
        public Common.ControlType FieldTypeID { get; set; }
        public string PickListEntity { get; set; }
        public bool PickListFromTable { get; set; }
        public string FieldUnit { get; set; }
        public string FieldLabel { get; set; }
    
        public virtual ICollection<DynamicGroupField> DynamicGroupField { get; set; }
        public virtual ICollection<CatalogItem> CatalogItem { get; set; }
        public virtual ICollection<QuoteVersionItem> QuoteVersionItem { get; set; }
        public virtual ICollection<BankField> BankField { get; set; }
    }
}
