//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRefubrish
    {
        public JobRefubrish()
        {
            this.JobRefubrish_Part = new HashSet<JobRefubrish_Part>();
        }
    
        public int JobID { get; set; }
        public string Loaction { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public int RefubrishStatusID { get; set; }
        public string ReportMemo { get; set; }
        public string ClinetNotes { get; set; }
        public Nullable<int> ReturningJobParentID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Job Job { get; set; }
        public virtual Job ParentJob { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual ICollection<JobRefubrish_Part> JobRefubrish_Part { get; set; }
        public virtual PickList RefubrishStatus { get; set; }
    }
}
