//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRefubrish_StepField
    {
        public int JobRefubrish_StepFieldID { get; set; }
        public int JobRefubrish_StepID { get; set; }
        public int DynamicGroupFieldID { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> SubGroupID { get; set; }
    
        public virtual JobRefubrish_Step JobRefubrish_Step { get; set; }
        public virtual DynamicGroupField DynamicGroupField { get; set; }
    }
}
