//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRefubrishStep
    {
        public JobRefubrishStep()
        {
            this.MachineTypeStep = new HashSet<MachineTypeStep>();
        }
    
        public int JobRefubrishStepID { get; set; }
        public string StepName { get; set; }
        public string FormName { get; set; }
        public int OrderVal { get; set; }
    
        public virtual ICollection<MachineTypeStep> MachineTypeStep { get; set; }
    }
}
