//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTask
    {
        public JobTask()
        {
            this.JobTaskEmployee = new HashSet<JobTaskEmployee>();
            this.JobTaskGroup = new HashSet<JobTaskGroup>();
        }
    
        public int JobTaskID { get; set; }
        public int JobID { get; set; }
        public string TaskName { get; set; }
        public string ManagerNotes { get; set; }
        public string EmpNotes { get; set; }
        public Nullable<int> JobRefubrishStepID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<JobTaskEmployee> JobTaskEmployee { get; set; }
        public virtual ICollection<JobTaskGroup> JobTaskGroup { get; set; }
    }
}
