//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTaskField
    {
        public int JobTaskFieldID { get; set; }
        public int JobTaskID { get; set; }
        public string FieldValue { get; set; }
        public int OrderVal { get; set; }
        public bool IsRequired { get; set; }
        public bool IsForQuote { get; set; }
        public int BankFieldID { get; set; }
    
        public virtual BankField BankField { get; set; }
        public virtual JobTask JobTask { get; set; }
    }
}
