//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTaskGroupField
    {
        public int JobTaskGroupFieldID { get; set; }
        public int JobTaskGroupID { get; set; }
        public int DynamicGroupFieldID { get; set; }
        public string FieldValue { get; set; }
        public int OrderVal { get; set; }
    
        public virtual JobTaskGroup JobTaskGroup { get; set; }
        public virtual DynamicGroupField DynamicGroupField { get; set; }
    }
}
