//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTemplateNotes
    {
        public int ID { get; set; }
        public Common.TemplateType JobType { get; set; }
        public string IL { get; set; }
        public string EN { get; set; }
    }
}
