//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVibration
    {
        public JobVibration()
        {
            this.JobVibrationMachine = new HashSet<JobVibrationMachine>();
            this.JobVibrationMachinePointResult = new HashSet<JobVibrationMachinePointResult>();
        }
    
        public int JobID { get; set; }
        public Nullable<int> TesterID { get; set; }
        public Nullable<int> AnalyzerID { get; set; }
    
        public virtual Employee Tester { get; set; }
        public virtual Employee Analayzer { get; set; }
        public virtual Job Job { get; set; }
        public virtual ICollection<JobVibrationMachine> JobVibrationMachine { get; set; }
        public virtual ICollection<JobVibrationMachinePointResult> JobVibrationMachinePointResult { get; set; }
    }
}
