//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVibrationMachine
    {
        public int JobID { get; set; }
        public int MachineID { get; set; }
        public string GeneralNoteIL { get; set; }
        public string GeneralNoteEN { get; set; }
        public string ClientNote { get; set; }
        public string ExtraNote { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public bool Flag { get; set; }
    
        public virtual JobVibration JobVibration { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
