//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVibrationMachinePointResult
    {
        public int JobVibrationMachinePointResultID { get; set; }
        public int JobID { get; set; }
        public int MachinePointID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ScheduleEntry { get; set; }
        public Nullable<int> Direction { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> Hide { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual JobVibration JobVibration { get; set; }
        public virtual MachinePoint MachinePoint { get; set; }
        public virtual PickList PickList { get; set; }
        public virtual PickList PickList1 { get; set; }
        public virtual PickList Status { get; set; }
    }
}
