//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LangString
    {
        public LangString()
        {
            this.Role = new HashSet<Role>();
        }
    
        public string Key { get; set; }
        public string EN { get; set; }
        public string IL { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
