//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinePoint
    {
        public MachinePoint()
        {
            this.JobVibrationMachinePointResult = new HashSet<JobVibrationMachinePointResult>();
        }
    
        public int MachinePointID { get; set; }
        public int MachineID { get; set; }
        public string PointNumber { get; set; }
        public Nullable<int> PointName { get; set; }
        public Nullable<int> HtmlX { get; set; }
        public Nullable<int> HtmlY { get; set; }
        public string Bearing { get; set; }
        public string Grease { get; set; }
        public string TrackWheels { get; set; }
        public string Track { get; set; }
        public string Tfrlok { get; set; }
        public string Connector { get; set; }
        public string GreaseAmount { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public bool ShowPoint { get; set; }
    
        public virtual ICollection<JobVibrationMachinePointResult> JobVibrationMachinePointResult { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
