//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinePart
    {
        public MachinePart()
        {
            this.JobRefubrish_Part = new HashSet<JobRefubrish_Part>();
            this.MachinePart_TechField = new HashSet<MachinePart_TechField>();
            this.JobAlignmentPart = new HashSet<JobAlignmentPart>();
        }
    
        public int MachinePartID { get; set; }
        public int MachineID { get; set; }
        public int MachineTypeID { get; set; }
        public string PartName { get; set; }
    
        public virtual ICollection<JobRefubrish_Part> JobRefubrish_Part { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual PickList MachineType { get; set; }
        public virtual ICollection<MachinePart_TechField> MachinePart_TechField { get; set; }
        public virtual ICollection<JobAlignmentPart> JobAlignmentPart { get; set; }
    }
}
