//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickList
    {
        public PickList()
        {
            this.JobVibrationMachinePointResult = new HashSet<JobVibrationMachinePointResult>();
            this.JobVibrationMachinePointResult1 = new HashSet<JobVibrationMachinePointResult>();
            this.JobVibrationMachinePointResult2 = new HashSet<JobVibrationMachinePointResult>();
            this.Machine = new HashSet<Machine>();
            this.Machine1 = new HashSet<Machine>();
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
            this.Request2 = new HashSet<Request>();
            this.User = new HashSet<User>();
            this.EmployeeRole = new HashSet<EmployeeRole>();
            this.MachinePart = new HashSet<MachinePart>();
            this.MachineTypeStep = new HashSet<MachineTypeStep>();
            this.SupplierProduct = new HashSet<SupplierProduct>();
            this.Quote = new HashSet<Quote>();
            this.Equipment = new HashSet<Equipment>();
            this.JobRefubrish = new HashSet<JobRefubrish>();
        }
    
        public int PickListID { get; set; }
        public string Entity { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Additional { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<JobVibrationMachinePointResult> JobVibrationMachinePointResult { get; set; }
        public virtual ICollection<JobVibrationMachinePointResult> JobVibrationMachinePointResult1 { get; set; }
        public virtual ICollection<JobVibrationMachinePointResult> JobVibrationMachinePointResult2 { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual ICollection<Machine> Machine1 { get; set; }
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<Request> Request1 { get; set; }
        public virtual ICollection<Request> Request2 { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRole { get; set; }
        public virtual ICollection<MachinePart> MachinePart { get; set; }
        public virtual ICollection<MachineTypeStep> MachineTypeStep { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProduct { get; set; }
        public virtual ICollection<Quote> Quote { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<JobRefubrish> JobRefubrish { get; set; }
    }
}
