//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteTalk
    {
        public int QuoteTalkID { get; set; }
        public int QuoteID { get; set; }
        public System.DateTime TalkDate { get; set; }
        public string Message { get; set; }
        public int CreatorID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
