//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteVersion
    {
        public QuoteVersion()
        {
            this.QuoteVersionItem = new HashSet<QuoteVersionItem>();
        }
    
        public int QuoteVersionID { get; set; }
        public int QuoteID { get; set; }
        public int Version { get; set; }
        public System.DateTime VersionDate { get; set; }
        public bool IsSelected { get; set; }
        public string Terms { get; set; }
        public string Appendices { get; set; }
        public decimal Disscount { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual ICollection<QuoteVersionItem> QuoteVersionItem { get; set; }
    }
}
