//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.Job = new HashSet<Job>();
            this.QuoteVersion = new HashSet<QuoteVersion>();
            this.QuoteTalk = new HashSet<QuoteTalk>();
        }
    
        public int QuoteID { get; set; }
        public string QuoteTitle { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int QuoteStatusID { get; set; }
        public string OrderNumber { get; set; }
        public string OrderAttachment { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime FollowDate { get; set; }
        public bool IsCover { get; set; }
        public Nullable<int> JobCardNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<Job> Job { get; set; }
        public virtual PickList QuoteStatus { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<QuoteVersion> QuoteVersion { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuoteTalk> QuoteTalk { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
