//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public int ClientID { get; set; }
        public int JobTypePL { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public int CtratedUserID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual User User { get; set; }
        public virtual PickList PickList { get; set; }
        public virtual PickList PickList1 { get; set; }
        public virtual PickList PickList2 { get; set; }
    }
}
