//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCatalogItemComponent
    {
        public int CatalogItemComponentID { get; set; }
        public int CatalogItemID { get; set; }
        public Common.CatalogItemType ComponentTypeID { get; set; }
        public int ComponentSrcID { get; set; }
        public int Quantity { get; set; }
        public decimal ComponentPrice { get; set; }
        public string ComponentName { get; set; }
        public decimal ComponentCost { get; set; }
    
        public virtual CatalogItem CatalogItem { get; set; }
    }
}
