//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientMachineCountHtmlImport
    {
        public int ClientID { get; set; }
        public string vwParentsName2 { get; set; }
        public Nullable<int> MachineCount { get; set; }
    }
}
