//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobVibrationGetPointAndStatus
    {
        public string PointNumber { get; set; }
        public string MachineName { get; set; }
        public int MachinePointID { get; set; }
        public int StatusID { get; set; }
        public int ClientID { get; set; }
    }
}
