//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobVibrationReport
    {
        public int JobID { get; set; }
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public int ClientID { get; set; }
        public string StatusLangStr { get; set; }
        public string JobVibrationMachineClientName { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public string JobVibrationClientName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string AnalyzerName { get; set; }
        public string TesterName { get; set; }
        public string Logo { get; set; }
        public Nullable<int> StatusValue { get; set; }
        public string StatusIL { get; set; }
        public string Details { get; set; }
        public string ClientName { get; set; }
        public string GeneralNoteIL { get; set; }
        public string GeneralNoteEN { get; set; }
        public string ClientNameEnglish { get; set; }
    }
}
