//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobVibration
    {
        public int JobID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime DueDate { get; set; }
        public string vwParentsName2 { get; set; }
        public int StatusID { get; set; }
        public string StatusLangStr { get; set; }
        public bool IsPosted { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string JobName { get; set; }
        public string AnalyzerName { get; set; }
        public string TesterName { get; set; }
        public string StatusValue { get; set; }
        public string ClientName { get; set; }
        public string vwChildsID { get; set; }
        public string ClientFullNameEnglish { get; set; }
    }
}
