//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobVibrationMachineLastStatus
    {
        public Nullable<int> ClientID { get; set; }
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> JobID { get; set; }
        public string WorstSts { get; set; }
        public string GeneralNoteIL { get; set; }
        public string GeneralNoteEN { get; set; }
    }
}
