//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQuoteReport
    {
        public string Status { get; set; }
        public int QuoteID { get; set; }
        public Nullable<decimal> itemTotal { get; set; }
        public System.DateTime FollowDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string EmpName { get; set; }
        public string ClientName { get; set; }
        public string WinStatus { get; set; }
    }
}
