//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        public static string A_About {
            get {
                return ResourceManager.GetString("A_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף.
        /// </summary>
        public static string A_Add {
            get {
                return ResourceManager.GetString("A_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה.
        /// </summary>
        public static string A_Change {
            get {
                return ResourceManager.GetString("A_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה תמונה.
        /// </summary>
        public static string A_ChangePicture {
            get {
                return ResourceManager.GetString("A_ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        public static string A_Continue {
            get {
                return ResourceManager.GetString("A_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        public static string A_Date {
            get {
                return ResourceManager.GetString("A_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        public static string A_Delete {
            get {
                return ResourceManager.GetString("A_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק תמונה.
        /// </summary>
        public static string A_DeletePicture {
            get {
                return ResourceManager.GetString("A_DeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכה.
        /// </summary>
        public static string A_Edit {
            get {
                return ResourceManager.GetString("A_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יורש.
        /// </summary>
        public static string A_Inherit {
            get {
                return ResourceManager.GetString("A_Inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום.
        /// </summary>
        public static string A_Loaction {
            get {
                return ResourceManager.GetString("A_Loaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        public static string A_Login {
            get {
                return ResourceManager.GetString("A_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התנתק.
        /// </summary>
        public static string A_Logout {
            get {
                return ResourceManager.GetString("A_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתוך.
        /// </summary>
        public static string A_Of {
            get {
                return ResourceManager.GetString("A_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עמוד.
        /// </summary>
        public static string A_Page {
            get {
                return ResourceManager.GetString("A_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי.
        /// </summary>
        public static string A_Private {
            get {
                return ResourceManager.GetString("A_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסוי.
        /// </summary>
        public static string A_Protected {
            get {
                return ResourceManager.GetString("A_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פומבי.
        /// </summary>
        public static string A_Public {
            get {
                return ResourceManager.GetString("A_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחזר.
        /// </summary>
        public static string A_Restore {
            get {
                return ResourceManager.GetString("A_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        public static string A_Save {
            get {
                return ResourceManager.GetString("A_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש.
        /// </summary>
        public static string A_Search {
            get {
                return ResourceManager.GetString("A_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלח דוא&quot;ל.
        /// </summary>
        public static string A_SendEmail {
            get {
                return ResourceManager.GetString("A_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלח הודעה.
        /// </summary>
        public static string A_SendMsg {
            get {
                return ResourceManager.GetString("A_SendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלח sms.
        /// </summary>
        public static string A_SendSms {
            get {
                return ResourceManager.GetString("A_SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות.
        /// </summary>
        public static string A_Settings {
            get {
                return ResourceManager.GetString("A_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשמה.
        /// </summary>
        public static string A_SignUp {
            get {
                return ResourceManager.GetString("A_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן.
        /// </summary>
        public static string A_Time {
            get {
                return ResourceManager.GetString("A_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן.
        /// </summary>
        public static string A_Update {
            get {
                return ResourceManager.GetString("A_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאום פגישה.
        /// </summary>
        public static string CallRequestIndex_RequestTest {
            get {
                return ResourceManager.GetString("CallRequestIndex_RequestTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאות שירות.
        /// </summary>
        public static string CallRequestIndex_Title {
            get {
                return ResourceManager.GetString("CallRequestIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שירות.
        /// </summary>
        public static string CallRequestPage_Title {
            get {
                return ResourceManager.GetString("CallRequestPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזרה לראשי.
        /// </summary>
        public static string Global_BackToHome {
            get {
                return ResourceManager.GetString("Global_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        public static string Global_Exit {
            get {
                return ResourceManager.GetString("Global_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות.
        /// </summary>
        public static string Global_Pereferences {
            get {
                return ResourceManager.GetString("Global_Pereferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חשמל מוטור.
        /// </summary>
        public static string HM {
            get {
                return ResourceManager.GetString("HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דחיפות.
        /// </summary>
        public static string Job_Priority {
            get {
                return ResourceManager.GetString("Job_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גבוהה.
        /// </summary>
        public static string JobPriority_High {
            get {
                return ResourceManager.GetString("JobPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נמוכה.
        /// </summary>
        public static string JobPriority_Low {
            get {
                return ResourceManager.GetString("JobPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בוצע.
        /// </summary>
        public static string JobStatus_Done {
            get {
                return ResourceManager.GetString("JobStatus_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ממתין.
        /// </summary>
        public static string JobStatus_Waiting {
            get {
                return ResourceManager.GetString("JobStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שירות.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איזונים דימניים.
        /// </summary>
        public static string JobType_Izunim {
            get {
                return ResourceManager.GetString("JobType_Izunim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיפוצים.
        /// </summary>
        public static string JobType_Shipotzim {
            get {
                return ResourceManager.GetString("JobType_Shipotzim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיוור בלייזר.
        /// </summary>
        public static string JobType_Shivur {
            get {
                return ResourceManager.GetString("JobType_Shivur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בדיקת רעידות.
        /// </summary>
        public static string JobType_Vibration {
            get {
                return ResourceManager.GetString("JobType_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מצב נוכחי.
        /// </summary>
        public static string JobVB_CurrentSts_Title {
            get {
                return ResourceManager.GetString("JobVB_CurrentSts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסטוריית בדיקות.
        /// </summary>
        public static string JobVB_HistoryIndex_Title {
            get {
                return ResourceManager.GetString("JobVB_HistoryIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *במידה ואינך זוכר את פרטי הכניסה, פנה למנהל המערכת שלך או לחברת חשמל מוטור.
        /// </summary>
        public static string Login_ForgotPassText {
            get {
                return ResourceManager.GetString("Login_ForgotPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין סיסמא.
        /// </summary>
        public static string Login_Password_Required {
            get {
                return ResourceManager.GetString("Login_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זכור אותי.
        /// </summary>
        public static string Login_RemeberMe {
            get {
                return ResourceManager.GetString("Login_RemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה למערכת.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להזין שם משתמש.
        /// </summary>
        public static string Login_UserName_Required {
            get {
                return ResourceManager.GetString("Login_UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Machine_Dashboard {
            get {
                return ResourceManager.GetString("Machine_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המכונה.
        /// </summary>
        public static string Machine_MachineName {
            get {
                return ResourceManager.GetString("Machine_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכונות.
        /// </summary>
        public static string Machine_Machines {
            get {
                return ResourceManager.GetString("Machine_Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזמנת שירות.
        /// </summary>
        public static string Machine_NewService {
            get {
                return ResourceManager.GetString("Machine_NewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס.
        /// </summary>
        public static string Machine_Status {
            get {
                return ResourceManager.GetString("Machine_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל.
        /// </summary>
        public static string Permission_Admin {
            get {
                return ResourceManager.GetString("Permission_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמש.
        /// </summary>
        public static string Permission_Member {
            get {
                return ResourceManager.GetString("Permission_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזמין.
        /// </summary>
        public static string Request_Creator {
            get {
                return ResourceManager.GetString("Request_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך בקשה.
        /// </summary>
        public static string Request_Date {
            get {
                return ResourceManager.GetString("Request_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאה חדשה.
        /// </summary>
        public static string Request_New {
            get {
                return ResourceManager.GetString("Request_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שירות.
        /// </summary>
        public static string Request_Request {
            get {
                return ResourceManager.GetString("Request_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאות שירות.
        /// </summary>
        public static string Request_RequestList {
            get {
                return ResourceManager.GetString("Request_RequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס קריאה.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת.
        /// </summary>
        public static string User_Address {
            get {
                return ResourceManager.GetString("User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות מנהל.
        /// </summary>
        public static string User_AdminPereferences {
            get {
                return ResourceManager.GetString("User_AdminPereferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפעל.
        /// </summary>
        public static string User_Client {
            get {
                return ResourceManager.GetString("User_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה סיסמא.
        /// </summary>
        public static string User_ChangePassword {
            get {
                return ResourceManager.GetString("User_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי התקשרות.
        /// </summary>
        public static string User_CommunicationDetails {
            get {
                return ResourceManager.GetString("User_CommunicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דוא&quot;ל.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פקס.
        /// </summary>
        public static string User_Fax {
            get {
                return ResourceManager.GetString("User_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון נייד.
        /// </summary>
        public static string User_Mobile {
            get {
                return ResourceManager.GetString("User_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמש חדש.
        /// </summary>
        public static string User_NewUser {
            get {
                return ResourceManager.GetString("User_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון משרדי.
        /// </summary>
        public static string User_OfficePhone {
            get {
                return ResourceManager.GetString("User_OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמא.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשאה.
        /// </summary>
        public static string User_Permission {
            get {
                return ResourceManager.GetString("User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטים אישיים.
        /// </summary>
        public static string User_PersonalDetails {
            get {
                return ResourceManager.GetString("User_PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        public static string User_Role {
            get {
                return ResourceManager.GetString("User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי משתמש.
        /// </summary>
        public static string User_UserDetails {
            get {
                return ResourceManager.GetString("User_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות משתמש.
        /// </summary>
        public static string User_UserPereferences {
            get {
                return ResourceManager.GetString("User_UserPereferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמשים.
        /// </summary>
        public static string User_Users {
            get {
                return ResourceManager.GetString("User_Users", resourceCulture);
            }
        }
    }
}
